### ISSUE TITLE
org.postgresql.util.PSQLException: ERROR: called `Result::unwrap()` on an `Err` value: NulError

### ISSUE THREAD

**Issue by lemon3853** [paradedb/pg_analytics#176]
### What happens?

use jdbc to query the .parquet table, an error message will be reported if the SQL statement contains in

### To Reproduce

```
PreparedStatement ps = dataSource.getConnection().prepareStatement("select mdbh, rq, txm, spmc, zj_dms, sx, xx, rcrq, zhxsrq, recent_7_day, recent_28_day, this_month, \n" +
        "la_month, half_year, last_year, curr_year from store_sale where mdbh = ? and rq = ?::date\n" +
        " and txm in ('8993175556996', '8992775344828')");

ps.setString(1, "0106");
ps.setString(2, "2024-11-14");
ResultSet resultSet = ps.executeQuery();

EntityListHandler handler = new EntityListHandler();
List<Entity> list1 = handler.handle(resultSet);
```

```
org.postgresql.util.PSQLException: ERROR: called `Result::unwrap()` on an `Err` value: NulError(178, [83, 69, 76, 69, 67, 84, 32, 109, 100, 98, 104, 44, 32, 114, 113, 44, 32, 116, 120, 109, 44, 32, 115, 112, 109, 99, 44, 32, 122, 106, 95, 100, 109, 115, 44, 32, 115, 120, 44, 32, 120, 120, 44, 32, 114, 99, 114, 113, 44, 32, 122, 104, 120, 115, 114, 113, 44, 32, 114, 101, 99, 101, 110, 116, 95, 55, 95, 100, 97, 121, 44, 32, 114, 101, 99, 101, 110, 116, 95, 50, 56, 95, 100, 97, 121, 44, 32, 116, 104, 105, 115, 95, 109, 111, 110, 116, 104, 44, 32, 108, 97, 95, 109, 111, 110, 116, 104, 44, 32, 104, 97, 108, 102, 95, 121, 101, 97, 114, 44, 32, 108, 97, 115, 116, 95, 121, 101, 97, 114, 44, 32, 99, 117, 114, 114, 95, 121, 101, 97, 114, 32, 70, 82, 79, 77, 32, 112, 117, 98, 108, 105, 99, 46, 115, 116, 111, 114, 101, 95, 115, 97, 108, 101, 32, 87, 72, 69, 82, 69, 32, 116, 120, 109, 32, 61, 32, 39, 1, 0, 0, 0, 0, 0, 0, 0, 25, 0, 0, 0, 2, 0, 0, 0, 1, 0, 0, 0, 68, 0, 0, 0, 56, 57, 57, 51, 49, 55, 53, 53, 53, 54, 57, 57, 54, 0, 0, 0, 68, 0, 0, 0, 56, 57, 57, 50, 55, 55, 53, 51, 52, 52, 56, 50, 56, 0, 0, 0, 39, 32, 65, 78, 68, 32, 109, 100, 98, 104, 32, 61, 32, 39, 48, 49, 48, 54, 39])

	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2725)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2412)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:371)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:502)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:419)
	at org.postgresql.jdbc.PgPreparedStatement.executeWithFlags(PgPreparedStatement.java:194)
	at org.postgresql.jdbc.PgPreparedStatement.executeQuery(PgPreparedStatement.java:137)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
```

### OS:

windows

### ParadeDB Version:

v0.8.0

### Are you using ParadeDB Docker, Helm, or the extension(s) standalone?

ParadeDB pg_analytics Extension

### Full Name:

lemon3853

### Affiliation:

xxx

### Did you include all relevant data sets for reproducing the issue?

Yes

### Did you include the code required to reproduce the issue?

- [X] Yes, I have

### Did you include all relevant configurations (e.g., CPU architecture, PostgreSQL version, Linux distribution) to reproduce the issue?

- [X] Yes, I have

**Comment by lemon3853** [comment]
use full SQL without error
![image](https://github.com/user-attachments/assets/19626774-440f-4f72-9375-0a7a82e9ed9f)

**Comment by lemon3853** [comment]
![image](https://github.com/user-attachments/assets/5dcae630-133b-482d-b420-91a24901d7a0)

If you don't use prepareStatement, you won't get an exception

**Comment by philippemnoel** [comment]
Hi there @lemon3853. ParadeDB is now on `v0.12.1`. You should report the `pg_analytics` version here. Please make sure you are on `v0.2.3`. We added support for PREPARE statements.
